[build]
  # Vite build command
  command = "npm run build"
  # Vite output directory
  publish = "dist"

# SPA redirect - handles React Router routes on refresh
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Redirect HTTP to HTTPS
[[redirects]]
  from = "http://zenniverse-ventures.netlify.app/*"
  to = "https://zenniverse-ventures.netlify.app/:splat"
  status = 301
  force = true

# Optional: Cache static assets for better performance
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
